name: Basic CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Change to frontend directory
        run: cd frontend

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build project (if you have a build script)
        run: npm run build
        working-directory: frontend

      - name: Check out code
        run: echo "The code has been checked out and dependencies have been installed successfully"
