name: Basic CI

on:
  push:

jobs:
  checkout_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check out code
        run: echo "The code has been checked out successfully"

